### ISSUE TITLE
Stalin sort fails

### ISSUE THREAD

**Issue by MetalBasket423** [gaming32/ArrayV-v4.0#106]
steps to reproduce:
open ArrayV without tweaking any settings
select stalin sort

expected behaviour:
sort completes normally with no errors

actual behaviour:
sort fails with error:
The sort was unsuccessful;
array[0] != validateArray[0]

Attached image of the error and ArrayV settings:
![Screenshot 2024-05-10 120950](https://github.com/Gaming32/ArrayV/assets/169443050/aa06d0e6-b9f5-4248-a670-3ef4cb66dd38)

**Comment by Gaming32** [comment]
The whole point of Stalin sort is that it fails in all cases where the array isn't already sorted.
