### ISSUE TITLE
How do i even open the program (not the jar file)

### ISSUE THREAD

**Issue by rylid-umil** [gaming32/ArrayV-v4.0#108]
The run.bat doesn't work, idk how to run just a file (run, no extension), and i have no idea how to use the mvnw, do i need to install maven or something? Also, i don't want to use the jar, because i'm trying to add a sort i'm making, and i can't just import it because, it wants a java file, not a js file and idk how to code a sort in a java source file... Also, i'm planning to fork this repo, and i don't think i can compile a jar file from my fork, so could somebody help

**Comment by EmeraldBlock** [comment]
Usually you just double-click or run in terminal, but I'm guessing you haven't installed the prerequisites. Regardless, a help question is not an issue with this repository; please join the Discord server (linked in the README) for help.

**Comment by rylid-umil** [comment]
i cant log into my discord acc for some reason

**Comment by rylid-umil** [comment]
i may have to wait since i will probably be able to log into my discord once i get the other device i used since i moved its still in my previous home town

**Comment by rylid-umil** [comment]
did ./mvnw clean verify, it said compilation failure. Realizeed im running on a JRE.

**Comment by rylid-umil** [comment]
Doing it again, switched to jdk-22 instead of jre-1.8. Suddenly after generating javadoc, got blasted with like 1000 warnings and stuff in like, 0.3 seconds. BUILD SUCCESS

**Comment by rylid-umil** [comment]
Just did ./run. seems nothing is happening

nothing happened but its not prompting me to type something yet

**Comment by rylid-umil** [comment]
IT RUN LETS FRIGGIN' GO
