### ISSUE TITLE
How do i run a single sort on different shuffles, as a script

### ISSUE THREAD

**Issue by rylid-umil** [gaming32/ArrayV-v4.0#109]
How do i make a script that runs a single sort on different kinds of shuffles? as far as I know, i have no idea

**Comment by EmeraldBlock** [comment]
As mentioned in https://github.com/Gaming32/ArrayV/issues/108#issuecomment-2165465971, help questions are not issues with the repository, so you should ask in the Discord server (or maybe in a GitHub discussion if you really don't want to leave the platform).
