### ISSUE TITLE
Error while trying to compile

### ISSUE THREAD

**Issue by MatTrof** [gaming32/ArrayV-v4.0#119]
when i try to compile it gives me the error ```Error: JAVA_HOME not found in your environment.
Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.```

**Comment by EmeraldBlock** [comment]
Please provide further details: Have you installed Java? What did you do to compile ArrayV up until this error occurred, and was there any other output?

My best guess is that the error message already tells you exactly what you need to fix.

**Comment by MatTrof** [comment]
> Please provide further details: Have you installed Java? What did you do to compile ArrayV up until this error occurred, and was there any other output?
> 
> My best guess is that the error message already tells you exactly what you need to fix.

sorry, i put JAVA_HOME into the wrong folder

it compiled now
