### ISSUE TITLE
Incorrect Run All Configuration

### ISSUE THREAD

**Issue by mingyue12** [gaming32/ArrayV-v4.0#27]
The run all configuration for all exchange sorts is incorrect.
The text that I underlined in the attached picture is "LRQuickSortParaell", which it should be "ReverseBubbleSort".
Please fix it for me.
![e](https://user-images.githubusercontent.com/63499942/113666794-02dce500-96da-11eb-8cdf-bd319623c44d.JPG)

**Comment by gaming32** [comment]
Thanks for notifying me about this!

**Comment by gaming32** [comment]
Fixed!
