### ISSUE TITLE
Parallel Block Merge mental breakdown

### ISSUE THREAD

**Issue by Gaming32** [Gaming32/ArrayV-v4.0#43]
Just run Parallel Block Merge Sort yourself and view the carnage.

For reference: https://youtu.be/0ae2q700NNc?t=8249

**Comment by EmeraldBlock** [comment]
seems to be caused by the changes to `Highlights.java`

**Comment by EmeraldBlock** [comment]
Cause identified: `Highlights.clearAllMarks()` was not synchronous. I have no clue how that fixes this.

**Comment by Gaming32** [comment]
Ah yes, threading without a GIL to keep you safe. ~~always fun~~

**Comment by EmeraldBlock** [comment]
`clearAllMarks()` is used by binary insertion sort which is used by parallel block merge, so I guess that's how it's relevant

still no clue how this alters the sort's behavior; the Highlights functions only modify Highlights properties
