### ISSUE TITLE
Sound periodically cuts out

### ISSUE THREAD

**Issue by PCBoyGames** [Gaming32/ArrayV-v4.0#58]
As the transition happens between Selection and Insertion, the sound disappears for the rest of the category, returning at Merge. https://www.youtube.com/watch?v=l3SS-cymAUg?t=2640

**Comment by EmeraldBlock** [comment]
~~Sounds~~ like an issue @Gaming32 mentioned before in the Discord server (<https://discord.com/channels/592082838791127075/724718756713988187/803789491738771476>), I don't know anything about it though

**Comment by Gaming32** [comment]
That sounds like the cause, yes. (pun very much not intended)
