### ISSUE TITLE
Sound delayed after sleep

### ISSUE THREAD

**Issue by Ibozz91** [Gaming32/ArrayV-v4.0#59]
If I shut my laptop, after opening it again, sound will be delayed in ArrayV.

**Comment by Gaming32** [comment]
Probably related to #58

**Comment by PCBoyGames** [comment]
From what I'm **_hearing_**, it might be similar, if not the same problematic code.

_What am I even doing..._

**Comment by EmeraldBlock** [comment]
seems to happen consistently and with a consistent delay

**Comment by EmeraldBlock** [comment]
A quick internet search shows <https://stackoverflow.com/questions/38944107/java-midi-audio-is-delayed-after-laptop-comes-out-of-hibernation>; does this match this situation?

**Comment by Gaming32** [comment]
That did in fact help solve the problem!
