### ISSUE TITLE
Some sorts access out-of-bounds indices

### ISSUE THREAD

**Issue by Ibozz91** [Gaming32/ArrayV-v4.0#61]
Some sorts are attempting to access indice 32768 on 32768 numbers, which is out of bounds. This does not happen on 2048 numbers.

**Comment by thatsOven** [comment]
this happens because ArrayV internally uses an array of size 32768 (unless you change it via command prompt when starting the program) so these sorts actually write out of bounds for every size, but you usually don't notice it because the array is actually bigger

**Comment by Gaming32** [comment]
On 2048 numbers, you should notice warnings being printed to the console.

**Comment by Ibozz91** [comment]
I think that there should be warnings instead of errors on higher numbers.

**Comment by EmeraldBlock** [comment]
There are warnings on sizes below the max because the out-of-bounds index actually exists, but on max size it's truly out of bounds and there is an error.

Whether warning or error, you'd probably need all sorts to access the array by "proxy" (since if they access it directly, the array would act as if it was max size).

Personally, I think it should always error, but that would break the problematic sorts.

**Comment by MusicTheorist** [comment]
> I think that there should be warnings instead of errors on higher numbers.

I actually disagree. Accessing out-of-bounds memory is a serious problem. In languages without Java's safety precautions, it leads to undefined behavior. Algorithms that have this issue should straight up be fixed without question.

**Comment by Ibozz91** [comment]
Okay. this sounds good. The sorts so far I have had problems with the psuedo-heap and grail sort.

**Comment by picc-lu** [comment]
I found same problem in Binary Merge sort, something wrong in Highlights:
**save index:**

- ![1](https://user-images.githubusercontent.com/32639909/125843225-6da5825f-2c10-47db-a144-d2dca387ca91.png)
- ![2](https://user-images.githubusercontent.com/32639909/125843168-69344ed6-4ceb-4634-b10f-7a0702fecd23.png)

**read index:**

- ![3](https://user-images.githubusercontent.com/32639909/125863599-d1a1c9b6-3ae5-4045-95d0-15d8ce06abe9.png)
- ![4](https://user-images.githubusercontent.com/32639909/125863607-66a99e15-1e3e-4101-84fc-39f87b97aea8.png)
- ![5](https://user-images.githubusercontent.com/32639909/125863609-7b84a267-c892-4ce9-8aa5-4e016cc0d13c.png)

Hope this will help.

**Comment by EmeraldBlock** [comment]
Yeah, once `low` or `high` reaches the end of its subarray, it just sits there and still gets highlighted

...wow those screenshots take up a lot of space lol

**Comment by Gaming32** [comment]
Related: #60

**Comment by Gaming32** [comment]
If sorts attempt to highlight out-of-bounds indices, the request to highlight is ignored. Attempting to write to out-of-bounds indices is still an error, however. This was such an easy fix, I have no clue why we didn't do it before.
