### ISSUE TITLE
Sorted check breaks on equal elements

### ISSUE THREAD

**Issue by Yuri-chan2007** [Gaming32/ArrayV-v4.0#65]
When I run a sort where the main array has equal elements, it says the sort was unsuccessful while it actually is.
Reference image:
![image](https://user-images.githubusercontent.com/63499942/125026653-423b1900-e0af-11eb-98db-5e9c0cc61f96.png)

**Comment by Gaming32** [comment]
What sort is this, and does this issue occur on other sorts?

**Comment by Yuri-chan2007** [comment]
Binary Pattern-Defeating Merge Sort, and it does occour on any non-esoteric sorts
