### ISSUE TITLE
not really an issue but

### ISSUE THREAD

**Issue by big-gay-dinosaur** [Gaming32/ArrayV-v4.0#69]
will there be an array writing api? like, you could write your own sorting algorithms or something, with some api and then it'll be sorted when you like compile and run it? idk but i think that is a really awesome idea

**Comment by Gaming32** [comment]
That's exactly how this program works! See the sorts in `src/sorts/` for examples.

**Comment by EmeraldBlock** [comment]
@big-gay-dinosaur in the future, please put a summary of the issue in the title! (also check out the [discord server](https://discord.com/invite/2xGkKC2) if you've got any questions about ArrayV)
