### ISSUE TITLE
Array size sliders much too close to eachother in Linux.

### ISSUE THREAD

**Issue by Apollyon094** [Gaming32/ArrayV-v4.0#71]
This is an issue in MATE and GNOME, not sure about KDE.

[picture](https://i.ibb.co/ysbZvm7/Screenshot-from-2021-11-01-08-33-57.png)

**Comment by EmeraldBlock** [comment]
gaming said it's due to a certain Swing API that's used

**Comment by Gaming32** [comment]
It's due to using Swing's PLAF system not working quite right on GNOME.
